input {
  tcp {
    mode => "server"
    host => "0.0.0.0"
    port => 4560
    codec => json_lines
    type => "info"
  }
}
filter {}
output {
  elasticsearch {
      action => "index"
      hosts => ["elasticsearch:9200"]
      user => "xxx"                # 用户名
      password => "xxx"       # 密码（不推荐明文）
      index => "xybjz-log-%{+YYYY.MM.dd}" #索引名
      manage_template => false
    }
}
