# 命令执行 docker-compose -f docker-compose-environment.yml up -d
version: '3.9'
services:
  # nacos
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    restart: always
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    networks:
      - my-network
    depends_on:
      mysql:
        condition: service_healthy


  mysql:
    image: mysql:8.0.32
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - my-network
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s #检查间隔
      timeout: 5s #超时时间
      retries: 3 #重试次数
      start_period: 10s #在服务启动后等待 10s 再开始健康检查


#  # phpmyadmin https://hub.docker.com/_/phpmyadmin
#  phpmyadmin:
#    image: phpmyadmin:5.2.1
#    container_name: phpmyadmin
#    hostname: phpmyadmin
#    restart: always
#    ports:
#      - "8899:80"
#    environment:
#      - PMA_HOST=mysql # mysql 的容器名
#      - PMA_PORT=3306
#      - MYSQL_ROOT_PASSWORD=123456
#    depends_on:
#      mysql:
#        condition: service_healthy
#    networks:
#      - my-network
#
#  # Redis
#  redis:
#    image: redis:6.2
#    container_name: redis
#    restart: always
#    hostname: redis
#    privileged: true
#    ports:
#      - "16379:6379"
#    volumes:
#      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
#    command: redis-server /usr/local/etc/redis/redis.conf
#    networks:
#      - my-network
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 5s
#      timeout: 5s
#      retries: 3
#      start_period: 10s
#
#  # RedisAdmin https://github.com/joeferner/redis-commander
#  redis-admin:
#    image: spryker/redis-commander:0.8.0
#    container_name: redis-admin
#    hostname: redis-commander
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#      - HTTP_USER=admin
#      - HTTP_PASSWORD=admin
#      - LANG=C.UTF-8
#      - LANGUAGE=C.UTF-8
#      - LC_ALL=C.UTF-8
#    networks:
#      - my-network
#    depends_on:
#      redis:
#        condition: service_healthy

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12.9
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: rabbitmq-server
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - my-network

  # Zookeeper
  zookeeper:
    image: zookeeper:3.9.0
    container_name: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    networks:
      - my-network

  # canal-server 伪装成mysql的从库
  canal-server:
    image: canal/canal-server:v1.1.7
    container_name: canal-server
    restart: unless-stopped
    ports:
      - "11111:11111"
    volumes:
      - ./canal-server/instance.properties:/home/admin/canal-server/conf/example/instance.properties
    depends_on:
      - mysql
    networks:
      - my-network

  # canal-adapter 负责数据分发
  canal-adapter:
    image: coopersoft/canal-adapter:v1.1.6
    container_name: canal-adapter
    restart: unless-stopped
    ports:
      - "8082:8081"
    volumes:
      - ./canal-adapter/application.yml:/opt/canal-adapter/conf/application.yml
      - ./canal-adapter/bootstrap.yml:/opt/canal-adapter/conf/bootstrap.yml3
      - ./canal-adapter/es7:/opt/canal-adapter/conf/es7
    depends_on:
      - canal-server
    networks:
      - my-network

  elasticsearch:
    image: elasticsearch:7.17.14
    ports:
      - '9200:9200'
      - '9300:9300'
    container_name: elasticsearch
    restart: always
    environment:
      - 'cluster.name=elasticsearch' # 设置集群名称为elasticsearch
      - 'discovery.type=single-node' # 以单一节点模式启动
      - "cluster.name=docker-cluster" # 设置名称
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m' # 设置使用jvm内存大小
    networks:
      - my-network

  kibana:
    image: kibana:7.17.14
    container_name: kibana
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - '5601:5601'
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 #设置访问elasticsearch的地址
      - I18N_LOCALE=zh-CN
    networks:
      - my-network
    depends_on:
      - elasticsearch

  # http://127.0.0.1:9090/xxl-job-admin admin/123456 - 安装后稍等会访问即可
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.1 #M1 Mac 更换镜像 kuschzzp/xxl-job-aarch64:2.4.0
    container_name: xxl-job-admin
    restart: always
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    links:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/xxl_job?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SERVER_PORT=9090
    networks:
      - my-network

  # 数据采集
  prometheus:
    image: bitnami/prometheus:2.47.2
    container_name: prometheus
    restart: always
    ports:
      - "9099:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network
  # 监控界面 账号密码 admin admin
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/etc/grafana
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
