# 命令执行 docker-compose -f docker-compose-app.yml up -d
services:
  xybjz-app:
    image: wanyj/xybjz-app:1.0
    container_name: xybjz-app
    restart: always
    ports:
      - "8091:8091"
    volumes:
      - ./log:/data/log
      - ./log/xybjz:/log/xybjz
    environment:
      JAVA_OPTS: >
        -Xms2G -Xmx2G -XX:+UseG1GC -Xss256k
        -Xlog:gc*:file=/log/xybjz/gc.log:time,tid,tags,level:filecount=5,filesize=100M
        -XX:+DisableExplicitGC
        -XX:MaxMetaspaceSize=512m
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/log/xybjz/heapdump.hprof
      PARAMS: ""
    networks:
      - my-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  xybjz-front:
    container_name: xybjz-front
    image: wanyj/xybjz-front:1.0
    restart: always
    networks:
      - my-network
    ports:
      - "8000:8000"
    environment:
      - UMI_APP_API_HOST=http://127.0.0.1:8091
      - UMI_APP_WS_HOST=ws://127.0.0.1:8091
#      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#    healthcheck:
#      test: [ "CMD", "wget", "--spider", "-q", "http://0.0.0.0:3000/" ]
#      interval: 1m
#      timeout: 10s
#      retries: 3

networks:
  my-network:
    driver: bridge
